name: Build Image Workflow

on:
  workflow_call:
    inputs:
      SERVICE1_REF:
        required: true
        type: string
      SERVICE2_REF:
        required: true
        type: string
    secrets:
      GH_ACCESS_TOKEN:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  clone_repos:
    name: Clone Repos
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Service1
        uses: actions/checkout@v3
        with:
          repository: tleerai/service1
          ref: ${{ inputs.SERVICE1_REF }}
          path: ./meta/service1
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Checkout Service2
        uses: actions/checkout@v3
        with:
          repository: tleerai/service2
          ref: ${{ inputs.SERVICE2_REF }}
          path: ./meta/service2
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - run: pwd
      - run: ls -lah

      - uses: actions/upload-artifact@v3
        with:
          name: repo-artifact
          path: ./meta # or ${{ github.workspace }}
          if-no-files-found: error

  service1:
    name: Service1
    needs: clone_repos
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Sandbox
        uses: actions/checkout@v3
        with:
          repository: tleerai/sandbox
          ref: ${{ inputs.SERVICE2_REF }}
          path: ./meta/service2
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - run: |
          pwd
          ls -lah

      - uses: actions/download-artifact@v3
        with:
          name: repo-artifact
          path: ./meta

      - run: |
          pwd
          ls -lah

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./meta

      - id: build_image_action
        uses: ./.github/actions/build-image
        with:
          SEMVER_TAG: ${{ inputs.SEMVER_TAG }}
          DOCKERFILE_PATH: ./meta/service1/Dockerfile
          IMAGE_NAME: service1
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  service2:
    name: Service2
    needs: clone_repos
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Sandbox
        uses: actions/checkout@v3
        with:
          repository: tleerai/sandbox

      - uses: actions/download-artifact@v3
        with:
          name: repo-artifact
          path: ./meta

#      - name: Display structure of downloaded files
#        run: ls -R
#        working-directory: ./meta

      - run: ls -lah
      - run: pwd
      - run: ls -lah ${{ github.workspace }}

      - id: build_image_action
        uses: ./.github/actions/build-image
        with:
          SEMVER_TAG: ${{ inputs.SEMVER_TAG }}
          DOCKERFILE_PATH: ./meta/service2/Dockerfile
          IMAGE_NAME: service2
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}