name: Build Image Workflow

on:
  workflow_call:
    inputs:
      SERVICE1_REF:
        required: true
        type: string
      SERVICE2_REF:
        required: true
        type: string
    secrets:
      GH_ACCESS_TOKEN:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  service1:
    name: Service1
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: tleerai/service1
          ref: ${{ inputs.SERVICE1_REF }}
          path: ./service1
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - run: ls -lah
      - run: pwd
      - run: ls -lah ./service1

  service2:
    name: Service2
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: tleerai/service2
          ref: ${{ inputs.SERVICE2_REF }}
          path: ./service2
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - run: ls -lah
      - run: pwd
      - run: ls -lah ./service2
      - run: ls -lah ../

#      - id: build_image_action
#        uses: ./.github/actions/build-image
#        with:
#          SEMVER_TAG: ${{ inputs.SEMVER_TAG }}
#          DOCKERFILE_PATH: ./gaize/dockerfiles/gaize/Dockerfile-meta
#          IMAGE_NAME: gaize
#          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
