name: Build Image Workflow

on:
  workflow_call:
    inputs:
      SERVICE1_REF:
        required: true
        type: string
      SERVICE2_REF:
        required: true
        type: string
    secrets:
      GH_ACCESS_TOKEN:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  clone_repos:
    name: Clone Repos
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Service1
        uses: actions/checkout@v3
        with:
          repository: tleerai/service1
          ref: ${{ inputs.SERVICE1_REF }}
          path: ./meta/service1
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Checkout Service2
        uses: actions/checkout@v3
        with:
          repository: tleerai/service2
          ref: ${{ inputs.SERVICE2_REF }}
          path: ./meta/service2
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - run: pwd
      - run: ls -lah ~

      - uses: actions/upload-artifact@v3
        with:
          name: repo-artifact
          path: ./meta # or ${{ github.workspace }}
          if-no-files-found: error

  service1:
    name: Service1
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout # Is this a checkout for the action or for the dockerfile or both?
        uses: actions/checkout@v3
#        with:
#          ref: ${{ inputs.SEMVER_TAG }}


      - uses: actions/download-artifact@v3
        with:
          name: repo-artifact
          path: ./meta

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./meta

#      - id: build_image_action
#        uses: ./.github/actions/build-image
#        with:
#          SEMVER_TAG: ${{ inputs.SEMVER_TAG }}
#          DOCKERFILE_PATH: ./gaize/dockerfiles/gaize/Dockerfile-meta
#          IMAGE_NAME: gaize
#          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

#      - id: build_image_action
#        uses: ./.github/actions/build-image
#        with:
#          SEMVER_TAG: ${{ inputs.SEMVER_TAG }}
#          DOCKERFILE_PATH: ./gaize/dockerfiles/gaize/Dockerfile-meta
#          IMAGE_NAME: gaize
#          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
